apiVersion : apps/v1
kind: Deployment
metadata:
  name: javascript 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript
  template:
    metadata:
      labels:
        app: javascript 
    spec:
      containers:
        - name: javascript 
          image: acrdemduoc.azurecr.io/javascript
          ports:
          - containerPort: 8080